### ISSUE TITLE
Broker should expose an option to mandate server_side_encryption

### ISSUE THREAD

**Issue by cnelson** [cloudfoundry-community/s3-broker#14]
The broker should expose an option that applies this policy to brokered buckets for applications that need to ensure all data in their buckets is encrypted at rest.

    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "DenyUnencryptedPut",
                "Effect": "Deny",
                "Principal": {
                    "AWS": "*"
                },
                "Action": "s3:PutObject",
                "Resource": ":BUCKET-ARN:/*",
                "Condition": {
                    "StringNotEquals": {
                        "s3:x-amz-server-side-encryption": "AES256"
                    }
                }
            }
        ]
    }

**Comment by jmcarp** [comment]
Another candidate for pairing with @jseppi.
