### ISSUE TITLE
Error while pushing the broker to PCF

### ISSUE THREAD

**Issue by blinse** [cloudfoundry-community/s3-broker#16]
I don't have much experience with AWS, but still would like to get this working ...

After adding the credentials of an IAM user to the manifest.yml file and doing a `cf push`, I get the following error: 

    11:29:26 Error loading config file: Validating config contents: Validating S3 configuration: Must provide a non-empty AwsPartition 

Looking at the config.json file, I realize that a resource name must be provided. So I edited the file to include the following line: 

    "Resource": ["arn:aws:s3:::here-is-my-bucket-name/*"]

Still I am getting the exact same error message. Not sure what is wrong.

**Comment by blinse** [comment]
Seems like an extra line must be added to the config.json file:

    $ diff -C 2 config-sample.json config.json
    *** config-sample.json	Thu May  4 12:40:47 2017
    --- config.json	Thu May  4 14:40:40 2017
    ***************
    *** 8,11 ****
    --- 8,12 ----
          "policy_prefix": "cf",
          "bucket_prefix": "cf",
    +     "aws_partition": "aws",
          "allow_user_provision_parameters": false,
          "allow_user_update_parameters": false,

Having added this line, the broker starts up without errors.

**Comment by muconsulting** [comment]
Hi,
Good catch - the _aws_partition_ entry was added to prevent the assumption that ARN's partition part was aws, to support other partitions, the partition is aws-partitionname. For example, the partition for resources in the China (Beijing) region is aws-cn.

**Comment by muconsulting** [comment]
Changes done.
