### ISSUE TITLE
Broker may want to allow provisioned users to access other buckets in the same org / space

### ISSUE THREAD

**Issue by cnelson** [cloudfoundry-community/s3-broker#19]
Currently the users provisioned by broker can only access the bucket associated with that service instance. While this should continue to be the default behavior there are use cases where a user may want one set of credentials that can access multiple brokered buckets.  

For example, an application may have a production bucket, and wish to replicate content from that bucket to a backup or staging bucket on a regular interval using the stock `aws s3 sync` command.  This is impossible if the source and destination buckets cannot be accessed with a single IAM credential.

My current thinking is that we should extend the broker to support parameters for create-service-key (and maybe bind-service?) to allow specifying other services instances that the provisioned user could access.  Something like this:

```bash
$ cf create-service s3 basic bucket-foo
$ cf create-service s3 basic bucket-bar

# create a service key for bucket-bar that also allows access to bucket-foo
$ cf create-service-key bucket-bar multi-bucket -c '{"additional_buckets": ["bucket-foo"]}'
```
The broker would then use the CF API to resolve the other service instances by name, and make it available to the iam policy template renderer.

WDYT @jmcarp @muconsulting ?

**Comment by cnelson** [comment]
cc: @mogul

**Comment by mogul** [comment]
Sounds good if it can be done cleanly. I'd mainly worry about an action on one of the bindings affecting others. So long as would only result in additional rather than shared/overlapping IAMs access, that seems like it would be unlikely. 

One thing to think about is how to communicate this situation back to the user in subsequent operations. Presumably we wouldn't give the existing bucket's credentials alongside the new set...? 🤔

**Comment by cnelson** [comment]
@mogul Each binding (or service key) creates it's own user so they shouldn't effect each other.

What I'm suggesting is we treat the binding as what is is --  a request to create a new iam user --
but we allow the caller to request that the user being created have additional permissions than what would be granted by default.

By requiring the caller to specify the name of a service instance in the current space (which the broker will resolve to an arn and error if the given name isn't in the current space) we ensure we maintain the CF abstraction of orgs/spaces as a permission boundary -- the caller cannot specify an arbitrary bucket or arn which may belong to another tenant.

**Comment by jmcarp** [comment]
I'm looking at this a bit today (always need more golang practice). I think the interface you're describing makes sense. I'm wondering how we should change the bind credentials. Replace `bucket` with `buckets`, and list all relevant buckets there? Keep `bucket`, and add an `additional_buckets` key with the others attached? I'm leaning toward the second option; WDYT?

**Comment by cnelson** [comment]
I also lean towards the second option we should preserve compatibility with existing apps who expect to find a 'bucket' key in the creds.

**Comment by brittag** [comment]
*Marking for my memory / ease of cross-referencing: [related ticket](https://cloud-gov.zendesk.com/agent/tickets/534)*
