### ISSUE TITLE
Dependency on CF client configuration not documented

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry-community/s3-broker#22]
[This commit](https://github.com/cloudfoundry-community/s3-broker/commit/3144f006e9165448e36362244eb8b8f7079ec743) adds a dependency that looks like some kind of UAA client needs to be created to run this service broker.

I can find no reference to documentation around this, and the result is that if you follow the instructions for deployment, you get an error:

``` 2017-09-08T14:13:19.91+1000 [APP/PROC/WEB/0] ERR 2017/09/08 04:13:19 Error creating CF client: Could not get api /v2/info: Get http://api.bosh-lite.com/v2/info: dial tcp 10.244.0.34:80: getsockopt: connection refused```

I'm still trying to understand why there is a dependency, and how it's been introduced... but in the interim, it'd be great if someone could update the config samples etc so that a server can start. :)

I'll do some archeology myself, and write up what I find here.

**Comment by jmcarp** [comment]
Improved docs in #24.
