### ISSUE TITLE
Enable option for FIPS endpoint

### ISSUE THREAD

**Issue by amaline** [cloudfoundry-community/s3-broker#37]
S3 supports FIPS compliant endpoints by adding the 's3-fips.' prefix to the endpoint URL.  For example:

- s3-fips.us-east-2.amazonaws.com
- s3-fips.us-gov-west-1.amazonaws.com

An option should be added to either provide a FIPS S3 plan, or as a user option during service creation

**Comment by bengerman13** [comment]
fixed in #39
