### ISSUE TITLE
Deleting non-empty buckets

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/s3-broker#8]
Trying to delete a bucket with objects in it fails currently. To preserve parity with https://github.com/cloudfoundry-community/s3-cf-service-broker, we could clear out all files on delete. But maybe that's not the right behavior--users might expect the broker to behave like aws and complain if they try to delete a non-empty bucket. We could also set this as an option on provision.

cc @cnelson

**Comment by afeld** [comment]
_Ideally_ there would be a prompt for confirmation or a "force" option that's required or something, but I wouldn't lose sleep over it, especially if the broker pattern doesn't support it. I haven't seen any other brokers do it.

**Comment by jmcarp** [comment]
The service broker api doesn't let us add prompts, and while some actions (provision, bind) allow for arbitrary parameters to get passed in, deprovision doesn't. So it looks like the options are: error on deleting a non-empty bucket; clear out all files on deleting a non-empty bucket; or allow users to decide that behavior on provision. I like the first option, since it's simple and mirrors the native aws behavior, but it does break parity with the existing broker.

**Comment by cnelson** [comment]
I agree, forcing the user to empty their bucket is a good check against them accidentally nuking important data in a bucket, and it can be accomplished with a single command: `aws s3 rm s3://bucket-name --recursive`.  As long as we document that clearly (can we include a link to the [relevant docs](http://docs.aws.amazon.com/AmazonS3/latest/dev/delete-or-empty-bucket.html#empty-bucket-awscli) in the error message returned when a non empty bucket is deprovisioned?) I don't see any reason to do extra work here.

**Comment by muconsulting** [comment]
I agree with @cnelson  - in my case I advocate users to empty their buckets first, prior operating a service delete request.

**Comment by rogeruiz** [comment]
> error on deleting a non-empty bucket

@jmcarp I think this is the best approach. This allows us to mimic the broker api without adding any additional cleverness. We should document the limitations about deleting non-empty buckets and provide the necessary documentation / information / `commands?` for users to fix the issue on their end.

**Comment by cnelson** [comment]
cloud.gov documentation updated in https://github.com/18F/cg-site/pull/655
